### ISSUE TITLE
Building the library using CMake

### ISSUE THREAD

**Issue by anderskaestner** [rwgk/sginfo#1]
I have implemented project files to build sginfo using CMake and would like to add these to the repository. 
The advantage of using CMake is that it is possible to fetch sginfo as a dependency during the build of another project that is built using CMake.

In particular, I'm currently working on the branch c2cpp of this project https://bitbucket.org/mirkoboin/nxs/src/master/

**Comment by rwgk** [comment]
Hi Anders, do you just want to add a file and leave everything else as is?
Did you consider using sglite instead?

   - https://github.com/rwgk/sglite # No known bugs but also no
   documentation.

I think it should be easy to replace sginfo with sglite. I could help
(pointers, answering questions).

**Comment by anderskaestner** [comment]
Hi Ralf,

I essentially only want to add two files for CMake, the rest untouched. The CMake files are only tested on MacOS, but I don’t expect any problems on Linux. Windows I didn’t try with CMake yet.

I didn’t consider using sglite yet. In principle, I’m just revising Mirko Boin’s code into C++ and to provide python bindings. What would be the advantage of using sglite?

Cheers

Anders

File 1 (CMakeLists.txt) contains:
# define minimum cmake version
cmake_minimum_required(VERSION 3.11 FATAL_ERROR)

# project name and supported language
project(sginfo LANGUAGES C)

# require C++11
#set(CMAKE_CXX_STANDARD 11)
#set(CMAKE_CXX_EXTENSIONS OFF)
#set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_subdirectory(sginfo_1_01)

File 2 (sginfo_1_01/CMakeLists.txt) contains:
add_definitions(-DVERSION="1.01")

add_library(sginfo
  SHARED

  sgclib.c
  sghkl.c
  sgio.c
  sgsi.c
  sgfind.c
  sginfo.c

  sginfo.h
  )

#target_link_libraries(sginfo
#  PUBLIC
#    sginfo::module
#
#  )

---
Paul Scherrer Institut
Dr. Anders Kaestner
Scientist, Neutron Imaging and Applied materials Group

**Comment by rwgk** [comment]
Adding the files we can do in any case. Do you prefer sending a pull
request are write access to the sginfo repo? I'm fine either way. What's
your github user name?

Advantage of using sglite: no known bugs. Did you look at the sginfo Known
Bugs <http://cci.lbl.gov/sginfo/#known_bugs> section?

**Comment by anderskaestner** [comment]
My github username is anderskaestner

For me it is probably easier with write access. Do you want me to push to master or via a branch?

Cheers

Anders

---
Paul Scherrer Institut
Dr. Anders Kaestner
Scientist, Neutron Imaging and Applied materials Group

**Comment by rwgk** [comment]
I just added you as a collaborator (push access).
Please push straight to master.

**Comment by anderskaestner** [comment]
Thanks, i already push my additions and tried it with my own projects. It seems like it works.

Thank you for letting me make this addition.

Cheers

Anders

---
Paul Scherrer Institut
Dr. Anders Kaestner
Scientist, Neutron Imaging and Applied materials Group

**Comment by rwgk** [comment]
Thank you Anders! Might be useful for the community :-)

**Comment by anderskaestner** [comment]
The Cmake files are added. I close this issue.
