### ISSUE TITLE
Install after compile

### ISSUE THREAD

**Issue by din14970** [rwgk/sginfo#3]
This might be a pretty stupid question but it is not clear to me how one actually installs the binary executable of sginfo on the path after cmake build. I tried cmake --install but the install configuration is empty. Any suggestions?

**Comment by rwgk** [comment]
Hi Niels, I just updated the main README with a `clang` (or `gcc`) command. Does that help?

I don't use cmake myself, but I know it only builds a shared library, not an executable.

**Comment by din14970** [comment]
Hi Ralf, thanks a lot for so quickly dealing with this noob question!
