### ISSUE TITLE
About the latest source code of sginfo. 

### ISSUE THREAD

**Issue by hongyi-zhao** [rwgk/sginfo#4]
I noticed the following description [here](http://cci.lbl.gov/sginfo/):

![image](https://user-images.githubusercontent.com/11155854/215238333-7f8f7f6e-16b7-4386-bc07-a652dab86e7e.png)

So, I would like to know if the latest development version of `sginfo` currently is located [here](https://github.com/cctbx/cctbx_project/tree/master/cctbx/sgtbx)?

Regards,
Zhao

**Comment by rwgk** [comment]
Yes, I think so.

I stopped working on the cctbx project, and crystallographic algorithms in
general, more than 10 years ago. I'm really out of touch at this point.
